config/routes.rb
Rails.application.routes.draw do
  get 'appliances/create'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #PAGES
  root 'static_pages#home'
  get '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'

  #POST REQUESTS
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'

  #DELETE
  delete '/logout', to: 'sessions#destroy'

  #RESOURCES
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :edit, :create, :update]
  resources :users do
    resources :appliances, only: [:new, :index, :create, :destroy, :update]
    resources :scenarios, only: [:new, :index, :create, :destroy]
    resources :scenario_of_appliances, only: [:new, :index, :create, :destroy]
  end


end

app/models/appliance.rb
class Appliance < ApplicationRecord
	has_many :performance_of_appliances, :dependent => :destroy
	validates :name, presence: true
	before_save :downcase_fields

	def downcase_fields
		self.name.downcase!
	end

end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController
	include AppliancesHelper
	U = 230
	before_action :index, only: :new
	before_action :get_my_rooms, only: :index

	def get_records_for(room_id)
		id = session[:user_id]
		records_for_specific_room = EntryRoom.where(user_id: id, room_id: room_id)
		@records = {}
		records_for_specific_room.each do |record|
			if @records[record.room.name] == nil
				@records[record.room.name] = {}
			end
			@records[record.room.name][record.entry.performance_of_appliance.appliance.name] = {appliance_id: record.entry.performance_of_appliance.appliance.id, entry_id: record.entry.id, room_id: record.room.id, performance: record.entry.performance_of_appliance.performance, count: record.entry.count}
		end
	end

	def create
		user = current_user

		PerformanceOfAppliance.transaction do
			text = params[:room]
			text = text.strip
			params[:room] = text.downcase
			@appliance = Appliance.where(name: params[:appliance][:name].downcase!).first_or_create(appliance_params)
			@performance_of_appliance = @appliance.performance_of_appliances.where(performance_of_appliance_params).first_or_create!(performance_of_appliance_params)
			@entry = @performance_of_appliance.entries.where(entry_params).first_or_create!(entry_params)
			@room = Room.where(name: params[:room]).first_or_create(name: params[:room])

			user.entry_rooms.where(user_id: user.id, entry_id: @entry.id, room_id: @room.id).first_or_create(user_id: user.id, entry_id: @entry.id, room_id: @room.id)

		end
		get_my_rooms
		get_records_for(@room.id)
		respond_to do |format|
			format.js {render 'appliances/create'}
		end
	end

	def update_scenarios(entry_room, old_count, new_count, old_performance, new_performance)
		if entry_room.scenario_of_appliances.any?
			entry_room.scenario_of_appliances.each do |scenario_of_appliance|
				scenario_of_appliance.update_attributes(number_of_up: new_count)
				scenario = scenario_of_appliance.scenario
				power = scenario.power - ((old_performance/U)*old_count) + ((new_performance/U)*new_count)
				scenario.update_attributes(power: power)
			end
		end

	end

	def update
		entry_room = EntryRoom.where(user_id: current_user.id, entry_id: params[:entry_id], room_id: params[:room_id]).first
		entry = entry_room.entry
		old_count = entry.count
		performance_of_appliance = entry.performance_of_appliance
		old_performance = performance_of_appliance.performance
		appliance = performance_of_appliance.appliance
		appliance_id = appliance.id
		performance_of_appliance_id = performance_of_appliance.id
		entry_id = entry.id
		appliance_can_delete = 0
		performance_can_delete = 0
		entry_can_delete = 0
		EntryRoom.transaction do
			if (appliance.name != params[:name].downcase!)
				if ((appliance_existing = Appliance.where(name: params[:name].downcase!)) && (appliance_existing.empty?))
					if(appliance.performance_of_appliances.length == 1)
						appliance.update_attributes(name: params[:name])
						appliance_id = appliance.id

					else
						appliance_id = Appliance.create(name: params[:name]).id
					end
				else
					if(appliance.performance_of_appliances.length == 1 && appliance_existing[0].id != appliance_id)
						appliance_can_delete = 1
					end
					appliance_id = appliance_existing[0].id
				end
				if ((performance_of_appliance_existing = PerformanceOfAppliance.where(appliance_id: appliance_id, performance: performance_of_appliance.performance)) && (performance_of_appliance_existing.empty?))
					if (performance_of_appliance.entries.length == 1)
						performance_of_appliance.update_attributes(appliance_id: appliance_id)
						performance_of_appliance_id = performance_of_appliance.id
					else
						performance_of_appliance_id = PerformanceOfAppliance.create(appliance_id: appliance_id, performance: performance_of_appliance.performance).id
					end
				else
					if(performance_of_appliance.entries.length == 1 && performance_of_appliance_existing[0].id != performance_of_appliance_id)
						performance_can_delete = 1
					end
					performance_of_appliance_id = performance_of_appliance_existing[0].id
				end
				if ((entry_existing = Entry.where(performance_of_appliance_id: performance_of_appliance_id, count: entry.count)) && (entry_existing.empty?))
					if (entry.entry_rooms.length == 1)
						entry.update_attributes(performance_of_appliance_id: performance_of_appliance_id)
						entry_id = entry.id
					else
						entry_id = Entry.create(performance_of_appliance_id: performance_of_appliance_id, count: entry.count).id
					end
				else
					if(entry.entry_rooms.length == 1 && entry_existing[0].id != entry_id)
						entry_can_delete = 1
					end
					entry_id = entry_existing[0].id
				end
			end
			if (performance_of_appliance.performance != params[:performance].to_i)
				if ((performance_of_appliance_existing = PerformanceOfAppliance.where(appliance_id: appliance_id, performance: params[:performance].to_i)) && (performance_of_appliance_existing.empty?))
					if (performance_of_appliance.entries.length == 1)
						performance_of_appliance.update_attributes(performance: params[:performance].to_i)
						performance_of_appliance_id = performance_of_appliance.id
					else
						performance_of_appliance_id = PerformanceOfAppliance.create(appliance_id: appliance_id, performance: params[:performance].to_i).id
					end
				else
					if(performance_of_appliance.entries.length == 1 && performance_of_appliance_existing[0].id != performance_of_appliance_id)
						performance_can_delete = 1
					end
					performance_of_appliance_id = performance_of_appliance_existing[0].id
				end
				if ((entry_existing = Entry.where(performance_of_appliance_id: performance_of_appliance_id, count: entry.count)) && (entry_existing.empty?))
					if (entry.entry_rooms.length == 1)
						entry.update_attributes(performance_of_appliance_id: performance_of_appliance_id)
						entry_id = entry.id
					else
						entry_id = Entry.create(performance_of_appliance_id: performance_of_appliance_id, count: entry.count).id
					end
				else
					if(entry.entry_rooms.length == 1 && entry_existing[0].id != entry_id)
						entry_can_delete = 1
					end
					entry_id = entry_existing[0].id
				end
			end
			if (entry.count != params[:count].to_i)
				if ((entry_existing = Entry.where(performance_of_appliance_id: performance_of_appliance_id, count: params[:count].to_i)) && (entry_existing.empty?))
					if (entry.entry_rooms.length == 1)
						entry.update_attributes(count: params[:count].to_i)
						entry_id = entry.id
					else
						entry_id = Entry.create(performance_of_appliance_id: performance_of_appliance_id, count: params[:count].to_i).id
					end
				else
					if(entry.entry_rooms.length == 1 && entry_existing[0].id != entry_id)
						entry_can_delete = 1
					end
					entry_id = entry_existing[0].id
				end
			end
			entry_room.update_attributes(entry_id: entry_id)
			update_scenarios(entry_room, old_count, entry_room.entry.count, old_performance, entry_room.entry.performance_of_appliance.performance)
			if (appliance_can_delete == 1)
				Appliance.find(appliance.id).destroy
			end
			if (performance_can_delete == 1)
				PerformanceOfAppliance.find(performance_of_appliance.id).destroy
			end
			if (entry_can_delete == 1)
				Entry.find(entry.id).destroy
			end
		end
		get_records_for(params[:room_id])
		respond_to do |format|
			format.js {render 'appliances/update'}
		end
	end

	def destroy
		entry_room = EntryRoom.where(user_id: params[:user_id], entry_id: params[:entry_id], room_id: params[:room_id]).first
		entry = entry_room.entry
		room = entry_room.room
		performance = entry.performance_of_appliance
		appliance = performance.appliance
		EntryRoom.transaction do
			if entry_room.scenario_of_appliances.any?
				entry_room.scenario_of_appliances.each do |scenario_of_appliance|
					scenario = scenario_of_appliance.scenario
					scenario_of_appliance.destroy
					if scenario.scenario_of_appliances.empty?
						scenario.destroy
					end
				end
			end
			entry_room.destroy
			if room.entry_rooms.empty?
				room.destroy
			end
			if entry.entry_rooms.empty?
				entry.destroy
			end
			if performance.entries.empty?
				performance.destroy
			end
			if appliance.performance_of_appliances.empty?
				appliance.destroy
			end
		end
		get_records_for(params[:room_id])
		respond_to do |format|
			format.js {render 'appliances/destroy'}
		end
	end

	def get_my_rooms
		id = session[:user_id]
		@rooms = EntryRoom.joins(:room).where("entry_rooms.user_id = ?", id).distinct("entry_rooms.room_id")
		@rooms = @rooms.map { |record|  record.room}
		@rooms.uniq!
	end

	def index
		respond_to do |format|
			if params[:room_id]
				get_records_for(params[:room_id])
				format.js{render 'appliances/showEntries'}
			else
				if @rooms.any?
					get_records_for(@rooms[0].id)
				end
				format.html{render 'index' }
			end
		end
	end


	private

	def appliance_params
		params.require(:appliance).permit(:name)
	end

	def performance_of_appliance_params
		params.permit(:performance, :appliance_id)
	end

	def entry_params
		params.permit(:count, :performance_of_appliance_id)
	end

	def room_params
		params.permit(:room)
	end

end

app/helpers/appliances_helper.rb
module AppliancesHelper


  def get_text(number)
    if number == 1
      return "1 kus"
    elsif number >= 2 && number <= 4
      return "#{number} kusy"
    else
      return "#{number} kusov"
    end
  end

end

app/views/appliances/_bigModal.html.erb
<!-- Modal -->
<div class="modal fade" id="bigModal" tabindex="-1" role="dialog" aria-labelledby="bigModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="bigModalLabel"></h4>
      </div>
      <%= form_tag(user_appliances_path(current_user), remote: true) do %>
          <div class="modal-body">
            <%= label_tag :room, "Miestnosť" %>
            <%= text_field_tag :room, params[:room], class: 'form-control' %>

            <%= fields_for :appliance do |builder| %>
                <%= builder.label :name, "Názov spotrebiča" %>
                <%= builder.text_field :name, class: 'form-control' %>
            <% end %>

            <%= label_tag :performance, "Výkon(W/h)" %>
            <%= number_field_tag :performance, params[:performance], class: 'form-control' %>

            <%= label_tag :count, "Počet" %>
            <%= number_field_tag :count, params[:count], class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Späť</button>
            <%= submit_tag "Uložiť", class: "btn btn-primary", id: "save-button" %>
          </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/appliances/_editModal.html.erb
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="editModalLabel">Uprav parametre spotrebiča</h4>
      </div>
      <%= form_tag(user_appliance_path(current_user,1), method: "patch", remote: true) do %>
          <div class="modal-body">
            <%= label_tag :name, "Názov spotrebiča" %>
            <%= text_field_tag :name, params[:name], class: 'form-control' %>

            <%= hidden_field_tag :entry_id, params[:entry_id], id: 'hidden-entry-id' %>
            <%= hidden_field_tag :room_id, params[:room_id], id: 'hidden-room-id' %>
            <%= hidden_field_tag :room, params[:room], id: 'hidden-room-name' %>

            <%= label_tag :performance, "Výkon(W/h)" %>
            <%= number_field_tag :performance, params[:performance], class: 'form-control' %>

            <%= label_tag :count, "Počet" %>
            <%= number_field_tag :count, params[:count], class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary", id: "save-button" %>
          </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/appliances/_entries.html.erb
<div class="row head-of-appliance-entry">
    <div class="col-md-3 col-xs-3">
      <b>Názov</b>
    </div>
    <div class="col-md-3 col-xs-4">
      <b>Výkon(W/h)</b>
    </div>
    <div class="col-md-3 col-xs-2">
      <b>Počet</b>
    </div>
</div>
<div id="body-table">
    <% if @records != nil %>
      <% @records.each do |key, appliances| %>
          <% appliances.each do |name, properties| %>
              <div class="row appliance-entry">
                <div class="col-md-3 col-xs-3">
                  <div><%= name.capitalize %></div>
                </div>
                <div class="col-md-3 col-xs-4">
                  <div class="appliance-properties-text"><%= properties[:performance] %></div>
                </div>
                <div class="col-md-3 col-xs-2">
                  <div class="appliance-properties-text"><%= properties[:count] %></div>
                </div>
                <div class="col-md-3 col-xs-3 UD-components">
                  <%= link_to '#',  data: {toggle: 'modal', target: '#editModal', appliance_id: properties[:appliance_id], entry_id: properties[:entry_id], room_id: properties[:room_id]}, class: 'update-appliance-button'  do %>
                      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                  <% end %>
                  <%= link_to user_appliance_path(current_user, properties[:appliance_id], entry_id: properties[:entry_id], room_id: properties[:room_id]), method: :delete, data: {confirm: "You sure?"}, remote: true, class: "deletion-appliance"  do %>
                      <span class="glyphicon glyphicon-remove" id="remove-component" aria-hidden="true"></span>
                  <% end %>
                </div>
              </div>
          <% end %>
      <% end %>
      <div class="row" id="add-button-row-background">
        <%= link_to "Pridaj spotrebič", '#', id: 'add-button-row',  data: {toggle: 'modal', target: '#smallModal'} %>
      </div>
    <% end %>
</div>

app/views/appliances/_menu.html.erb
  <% if @rooms != nil %>
    <% @rooms.each_with_index do |room, index| %>
        <% if index == 0 %>
          <li class="active">
        <% else %>
           <li>
        <% end %>
          <%= link_to  user_appliances_path(current_user, room_id: room.id), remote: true, class: 'rooms-nav-link' do %>
              <%= room.name.capitalize %>
          <% end %>
        </li>
    <% end %>
  <% end %>
  <li id="add-button-li-background">
    <%= link_to "Pridaj miestnosť", '#', id: 'add-button-li',  data: {toggle: 'modal', target: '#bigModal'}  %>
  </li>

app/views/appliances/_newAppliance.html.erb
<div class="row appliance-entry">
  <div class="col-md-3 col-xs-3">
    <%= @appliance.name.capitalize %>
  </div>
  <div class="col-md-3 col-xs-3">
    <%= @performance_of_appliance.performance %>
  </div>
  <div class="col-md-3 col-xs-3">
    <%= @entry.count %>
  </div>
  <div class="col-md-3 col-xs-3 UD-components">
    <%= link_to user_appliance_path(current_user, @appliance.id, entry_id: @entry.id, room_id: @room.id), method: :delete, data: {confirm: "You sure?"}  do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <% end %>
    <%= link_to user_appliance_path(current_user, @appliance.id, entry_id: @entry.id, room_id: @room.id), method: :delete, data: {confirm: "You sure?"}, remote: true, class: "deletion"  do %>
        <span class="glyphicon glyphicon-remove" id="remove-component" aria-hidden="true"></span>
    <% end %>
  </div>
</div>

app/views/appliances/_smallModal.html.erb
<!-- Modal -->
<div class="modal fade" id="smallModal" tabindex="-1" role="dialog" aria-labelledby="smallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="smallModalLabel"></h4>
      </div>
      <%= form_tag(user_appliances_path(current_user), remote: true) do %>
          <div class="modal-body">
            <%= fields_for :appliance do |builder| %>
                <%= builder.label :name, "Názov spotrebiča" %>
                <%= builder.text_field :name, class: 'form-control' %>
            <% end %>

            <%= hidden_field_tag :room, params[:room], id: 'hidden-room-name' %>

            <%= label_tag :performance, "Výkon(W/h)" %>
            <%= number_field_tag :performance, params[:performance], class: 'form-control' %>

            <%= label_tag :count, "Počet" %>
            <%= number_field_tag :count, params[:count], class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Späť</button>
            <%= submit_tag "Uložiť", class: "btn btn-primary", id: "save-button" %>
          </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/appliances/create.js.erb
if($('#bigModal').is(':visible')){
    $('#text').html("ha");
    $('.nav-pills').html("")
        .append("<%= escape_javascript render(partial: "menu") %>");

    $('#bigModal').modal('hide')
        .find("input[type=text],input[type=number]").val('');
    $('#bigModal #bigModalLabel').text('');
}
else if($('#smallModal').is(':visible')){
    var room_in_modal = $( '#smallModalLabel' ).text();
    var room_in_li_tag;
    $('.nav-pills > li').each(function(){
        room_in_li_tag = $(this).find('a').text();
        if (room_in_li_tag == room_in_modal){
            $('#body-table').append()
            $("<%= escape_javascript render(partial: "newAppliance") %>").insertAfter($('[class^="row appliance-entry"]').last());
            return false;
        }
    })
    $('#smallModal').modal('hide')
                    .find("input[type=text],input[type=number]").val('');
}

app/views/appliances/destroy.js.erb
$('.deletion-appliance').bind('ajax:success', function() {
    $(this).closest('.appliance-entry').slideUp(500, function() {
        $(this).remove();
    });
});

app/views/appliances/index.html.erb
<%= render partial: "bigModal" %>
<%= render partial: "smallModal" %>
<%= render partial: "editModal" %>
<span id="rooms-span" class="<%= if @rooms.any?
                                   @rooms[0].name
                                 end %>"></span>
<div class="row">
  <div class="col-md-3">
    <!-- It can be fixed with bootstrap affix http://getbootstrap.com/javascript/#affix-->
    <div id="sidebar" class="well sidebar-nav">
      <h5><i class="glyphicon glyphicon-home"></i>
        <small><b>MIESTNOSTI V DOMÁCNOSTI</b></small>
      </h5>
      <ul class="nav nav-pills nav-stacked">
        <%= render partial: "menu", locals: {rooms: @rooms } %>
        <div id="text">

        </div>
      </ul>




    </div>
  </div>
  <div class="col-md-9" id="table_entries">
    <% if @rooms.any? %>
      <%= render partial: "entries", locals: {hash_of_recrods: @hash_of_records } %>
    <% else %>
      <p class="no-entries">Nemáš uložené žiadne elektrické spotrebiče...</p>
    <% end %>
  </div>
</div>

app/views/appliances/showEntries.js.erb
$('#table_entries').html("")
    .append("<%= escape_javascript render(partial: "entries", locals: {hash_of_recrods: @hash_of_records }) %>");

app/views/appliances/update.js.erb
$('#table_entries').html("")
    .append("<%= escape_javascript render(partial: "entries", locals: {hash_of_recrods: @hash_of_records }) %>");
$('#editModal').modal('hide')
    .find("input[type=text],input[type=number]").val('')