config/routes.rb
Rails.application.routes.draw do
  get 'appliances/create'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #PAGES
  root 'static_pages#home'
  get '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'

  #POST REQUESTS
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'

  #DELETE
  delete '/logout', to: 'sessions#destroy'

  #RESOURCES
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :edit, :create, :update]
  resources :users do
    resources :appliances, only: [:new, :index, :create, :destroy, :update]
    resources :scenarios, only: [:new, :index, :create, :destroy]
    resources :scenario_of_appliances, only: [:new, :index, :create, :destroy]
  end


end

app/models/scenario.rb
class Scenario < ApplicationRecord
	has_many :scenario_of_appliances, :dependent => :destroy
	belongs_to :user
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
    include ScenariosHelper
    U = 230
    before_action :get_my_records, only: :new

  def index
  end

  def destroy
    scenario = Scenario.find(params[:id])
    Scenario.transaction do
        scenario.scenario_of_appliances.delete_all
        scenario.destroy
    end
    get_my_scenarios
    respond_to do |format|
      format.js{render 'scenarios/destroy'}
    end
  end

  def new
  end

  def create
    entry_room_ids = params[:entry_rooms]
    if(Scenario.count == 0)
      id = 0
    else
      id = Scenario.last.id + 1
    end

    i = 0

    Scenario.transaction do
      scenario = Scenario.new(id: id, user_id: current_user.id)
      entry_room_ids.each do |entry_room_id|
        entry_room = EntryRoom.where(id: entry_room_id)[0]
        performance = entry_room.entry.performance_of_appliance.performance
        i += ((performance/U)*entry_room.entry.count)
      end
      scenario.power = i
      if scenario.save == false
        flash[:danger] = "Nepodarilo sa vytvoriť scenár používaných spotrebičov."
      end
      entry_room_ids.each do |entry_room_id|
        entry_room = EntryRoom.where(id: entry_room_id)[0]
        ups = entry_room.entry.count
        soa = ScenarioOfAppliance.new(number_of_up: ups, scenario_id: scenario.id, entry_room_id: entry_room_id)
        if soa.save
          flash[:success] = "Vytvorili ste si scenár používaných spotrebičov. Pre náhľad choďte na stránku Domov."
        else
          flash[:danger] = "Nepodarilo sa vytvoriť scenár používaného spotrebiča."
        end
      end
    end
    redirect_to(new_user_scenario_path(current_user))
  end

  private

  def get_my_records
    @id = session[:user_id]
    @my_records = EntryRoom.where(user_id: @id)
    @records = {}
    @my_records.each do |record|
      if @records[record.room.name] == nil
        @records[record.room.name] = {}
      end
      @records[record.room.name][record.entry.performance_of_appliance.appliance.name] = {appliance_id: record.entry.performance_of_appliance.appliance.id, entry_id: record.entry.id, room_id: record.room.id, performance: record.entry.performance_of_appliance.performance, count: record.entry.count}
    end
  end

end

app/helpers/scenarios_helper.rb
module ScenariosHelper
  def get_my_scenarios
    @scenarios = Scenario.where(user_id: current_user).order(power: :desc)
  end
end

app/views/scenarios/_entries.html.erb
  <% i = 0 %>
  <%= form_tag(user_scenarios_path(current_user), remote: true) do %>
    <% @records.each do |key, appliances| %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <% if i == 0 %>
              <a role="button" class="collapsible-link" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i %>" aria-expanded="true" aria-controls="collapse<%= i %>">
                <%= key %>
              </a>
              <% else %>
              <a role="button" class="collapsible-link" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i %>" aria-expanded="false" aria-controls="collapse<%= i %>">
                <%= key %>
              </a>
              <% end %>
            </h4>
          </div>
          <% if i == 0 %>
          <% else %>

          <% end %>
          <% if i == 0 %>
              <div id="collapse<%= i %>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne" aria-expanded="true">
                <div class="panel-body">
                  <div class="row head-of-appliance-entry">
                    <div class="col-md-3 col-xs-4">
                      <b>Názov</b>
                    </div>
                    <div class="col-md-3 col-xs-4">
                      <b>Výkon(W/h)</b>
                    </div>
                    <div class="col-md-3 col-xs-2">
                      <b>Počet</b>
                    </div>
                  </div>
                  <% appliances.each do |name, properties| %>
                      <div class="row appliance-entry">
                        <div class="col-md-3 col-xs-4">
                          <div><%= name.capitalize %></div>
                        </div>
                        <div class="col-md-3 col-xs-4">
                          <div class="performance-text"><%= properties[:performance] %></div>
                        </div>
                        <div class="col-md-3 col-xs-2">
                          <div><%= properties[:count] %></div>
                        </div>
                        <div class="col-md-3 col-xs-2 UD-components">
                          <%= check_box_tag 'entry_rooms[]', EntryRoom.where(user_id: current_user, entry_id: properties[:entry_id], room_id: properties[:room_id])[0].id %>
                        </div>
                      </div>
                  <% end %>
                </div>
              </div>
          <% else %>
              <div id="collapse<%= i %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                  <div class="row head-of-appliance-entry">
                    <div class="col-md-3 col-xs-4">
                      <b>Názov</b>
                    </div>
                    <div class="col-md-3 col-xs-4">
                      <b>Výkon(W/h)</b>
                    </div>
                    <div class="col-md-3 col-xs-2">
                      <b>Počet</b>
                    </div>
                  </div>
                  <% appliances.each do |name, properties| %>
                      <div class="row appliance-entry">
                        <div class="col-md-3 col-xs-4">
                          <div><%= name.capitalize %></div>
                        </div>
                        <div class="col-md-3 col-xs-4">
                          <div class="performance-text"><%= properties[:performance] %></div>
                        </div>
                        <div class="col-md-3 col-xs-2">
                          <div><%= properties[:count] %></div>
                        </div>
                        <div class="col-md-3 col-xs-2 UD-components">
                          <%= check_box_tag 'entry_rooms[]', EntryRoom.where(user_id: current_user, entry_id: properties[:entry_id], room_id: properties[:room_id])[0].id %>
                        </div>
                      </div>
                  <% end %>
                </div>
              </div>
          <% end %>
        </div>
        <% i += 1 %>
    <% end %>
    <%= submit_tag "Vytvor scenar", class: "btn btn-primary", id: "create-scenario-button" %>
  <% end %>

app/views/scenarios/_scenarios.html.erb
<% @scenarios.each_with_index do |scenario, index| %>
    <div class="scenario">
      <div class="scenario-around">
        <span class="important-text">Scenár <%= index+1 %></span>
        <%= link_to user_scenario_path(current_user, scenario.id), method: :delete, data: {confirm: "You sure?"}, remote: true, class: "deletion-scenario"  do %>
            <span class="glyphicon glyphicon-remove" id="remove-component" aria-hidden="true"></span>
        <% end %>
        <div class="scenario-information">
            <% scenario.scenario_of_appliances.each do |scenario_of_appliance| %>
                <div class="row scenario-entry">
                  <div class="col-md-2 col-xs-4">
                    <%= scenario_of_appliance.entry_room.room.name %>
                  </div>
                  <div class="col-md-2 col-xs-4">
                    <%= scenario_of_appliance.entry_room.entry.performance_of_appliance.appliance.name %>
                  </div>
                  <div class="col-md-2 col-xs-4">
                    <span><%= get_text(scenario_of_appliance.number_of_up) %> </span>
                  </div>
                </div>

            <% end %>
          </div>
      </div>
      <div class="result-around">
        <p class="result-line"> Záťaž: <span class="result-text"><%= scenario.power %> A</span></p>
      </div>
    </div>
<% end %>

app/views/scenarios/destroy.js.erb
$('.deletion-scenario').bind('ajax:success', function() {
    var scenario = $(this).closest( '.scenario' );
    scenario.slideUp(500, function() {
        (this).remove();
    });

});

app/views/scenarios/index.html.erb
<% provide(:title, 'Dashboard') %>
<h1>Scenáre naraz používaných spotrebičov</h1>

  <div class = "row">
    <%= link_to "Vytvor", new_user_scenario_path(current_user), class: "btn btn-primary", id: "new-scenario-button" %>
  </div>
<% if @scenarios == nil or @scenarios.empty? %>
    <p class="no-entries">Nemáš vytvorené žiadne scenáre...</p>
<% else %>
    <%= render partial: "scenarios/scenarios" %>
<% end %>
<br>
<h1>Ceny za pripojenie do distribučnej sústavy na rok 2017 (ZSE)</h1>
<br>
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Istič</th>
      <th>Cena/rok</th>
    </tr>
    </thead>
    <tbody>
    <% flag = 0 %>
    <% @amper_price_west.each do |key, value| %>
      <% if @scenarios.any? && flag == 0 && 3*key - 1 > @scenarios[0].power %>
        <tr class="warning">
          <td><b>3x<%= key %> A</b></td>
          <td><b><%= value %> €</b></td>
          <% flag = 1 %>
      <% else %>
        <tr>
          <td>3x<%= key %> A</td>
          <td><%= value %> €</td>
      <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<h1>Ceny za pripojenie do distribučnej sústavy na rok 2017 (VSE)</h1>
<br>
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Istič</th>
      <th>Cena/rok</th>
    </tr>
    </thead>
    <tbody>
    <% flag = 0 %>
    <% @amper_price_east.each do |key, value| %>
        <% if @scenarios.any? && flag == 0 && 3*key - 2 > @scenarios[0].power %>
            <tr class="warning">
              <td><b>3x<%= key %> A</b></td>
              <td><b><%= value %> €</b></td>
              <% flag = 1 %>
        <% else %>
            <tr>
              <td>3x<%= key %> A</td>
              <td><%= value %> €</td>
        <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/scenarios/new.html.erb
<% provide(:title, 'Appliances') %>
<% if @records.any? %>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <%= render partial: "entries" %>
    </div>
<% else %>
    <p class="no-entries">Nemáš uložené žiadne elektrické spotrebiče...</p>
<% end %>