config/routes.rb
Rails.application.routes.draw do
  get 'appliances/create'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #PAGES
  root 'static_pages#home'
  get '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'

  #POST REQUESTS
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'

  #DELETE
  delete '/logout', to: 'sessions#destroy'

  #RESOURCES
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :edit, :create, :update]
  resources :users do
    resources :appliances, only: [:new, :index, :create, :destroy, :update]
    resources :scenarios, only: [:new, :index, :create, :destroy]
    resources :scenario_of_appliances, only: [:new, :index, :create, :destroy]
  end


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Home Appliances</a>
    by <a href="http://www.michaelhartl.com/">Martin Zak</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Úvodná stránka", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <% if logged_in? %>
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
          class="icon-bar"></span><span class="icon-bar"></span>
          </button>
          <%= link_to "Domáce spotrebiče",user_appliances_path(current_user), class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active">
              <%= link_to user_path(current_user) do %>
                <span class="glyphicon glyphicon-home"></span>Domov
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li>
              <%= link_to user_appliances_path(current_user), id: 'appliance' do %>
                <span class="glyphicon glyphicon-calendar"></span>Spotrebiče
              <% end %>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span
            class="glyphicon glyphicon-user"></span>User <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <span class="glyphicon glyphicon-cog"></span>Nastavenia
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to logout_path, method: "delete" do %>
                    <span class="glyphicon glyphicon-off"></span>Odhlásiť sa
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Prihlásiť sa", login_path %></li>
          </ul>
      <% end %>
      <!-- /.navbar-collapse -->
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-101591852-1', 'auto');
        ga('send', 'pageview');

    </script>
  </body>
</html>